### ISSUE TITLE
i got these

### ISSUE THREAD

**Issue by camoboy31** [MCMrARM/mc-w10-version-launcher#100]
![image](https://user-images.githubusercontent.com/67425597/113866054-c0cca580-97a4-11eb-8c6a-6814fefcee6f.png)
and this
![image](https://user-images.githubusercontent.com/67425597/113866182-e9ed3600-97a4-11eb-82f0-0c4084e514d0.png)
i dont know what dylan work is cuz its not on my computer either

**Comment by thanpixel** [comment]
I get the same errors. Some people were saying to just run the .appx file but it's not there
![image](https://user-images.githubusercontent.com/81921873/113955792-69e9bf00-97ea-11eb-9be2-0ee2a11a488a.png)

**Comment by Miruzaa** [comment]
Turn on Developer Mode on Windows 10 Settings

**Comment by Miruzaa** [comment]
> I get the same errors. Some people were saying to just run the .appx file but it's not there
> ![image](https://user-images.githubusercontent.com/81921873/113955792-69e9bf00-97ea-11eb-9be2-0ee2a11a488a.png)

Turn on Developer Mode on Windows 10 Settings

**Comment by camoboy31** [comment]
developermode was on

**Comment by DamianXAkuma** [comment]
i installed MCLAuncher and now my Minecraft Windows 10 is gone and i have to repay for it in the shop any help to fix this?
