### ISSUE TITLE
App re-register failed even though minecraft from store is not installed

### ISSUE THREAD

**Issue by Xenobotical** [MCMrARM/mc-w10-version-launcher#101]
![image](https://user-images.githubusercontent.com/78705130/113922399-8a644a00-97e7-11eb-8a12-dfb1307e58c4.png)
how do i fix this?

**Comment by Miruzaa** [comment]
Turn on Developer Mode on Windows 10 Settings

**Comment by Rekalh** [comment]
had the same issue even with Developer mode enabled

**Comment by DamianXAkuma** [comment]
i installed MCLAuncher and now my Minecraft Windows 10 is gone and i have to repay for it in the shop any help to fix this?
