### ISSUE TITLE
help me pls

### ISSUE THREAD

**Issue by KOTHACK** [MCMrARM/mc-w10-version-launcher#106]
![Screenshot_118](https://user-images.githubusercontent.com/50361317/115596270-97516500-a2e0-11eb-928c-64c1cb034652.png)

**Comment by lolpippiou** [comment]
Could you please translate the Russian text or at least try to?

**Comment by DamianXAkuma** [comment]
Yeah i installed MCLAuncher and now my Minecraft Windows 10 is gone and i have to repay for it in the shop any help to fix this?
