### ISSUE TITLE
 Download Failed When Im going To Download beta version.

### ISSUE THREAD

**Issue by Cloudy408** [MCMrARM/mc-w10-version-launcher#107]
So, When I Going to Download Beta version Of Minecraft Windows 10.
I Get This Error:
![Screenshot (16)](https://user-images.githubusercontent.com/74233896/115854473-79a50c80-a454-11eb-9f26-9ae437bbb367.png)

**Comment by Cloudy408** [comment]
Can Someone Help me pls

**Comment by Cloudy408** [comment]
But, When I Download Official version Its downloading With No Error

**Comment by cda94581** [comment]
This has been known for a while now.

**Comment by Cloudy408** [comment]
So, There Ia a Way To Fix It?

**Comment by Cloudy408** [comment]
I was enable developer mode but same error again

**Comment by dktapps** [comment]
Your account needs to be subscribed to the beta program in Xbox Insider Hub.

**Comment by Cloudy408** [comment]
ok
