### ISSUE TITLE
Can't install beta versions

### ISSUE THREAD

**Issue by AlicanCopur** [MCMrARM/mc-w10-version-launcher#108]
I can't install beta versions and got an error message.
![image](https://user-images.githubusercontent.com/37244649/115959539-5ee69c80-a515-11eb-9067-275530799c77.png)

**Comment by dktapps** [comment]
https://github.com/MCMrARM/mc-w10-version-launcher#prerequisites

> If you want to be able to use beta versions, you'll additionally need to subscribe to the Minecraft Beta program using Xbox Insider Hub.

**Comment by AlicanCopur** [comment]
I already subscribed to the Beta program.

**Comment by lolpippiou** [comment]
> I already subscribed to the Beta program.

Maybe try waiting a few days and it should work.
