### ISSUE TITLE
1.17 not launching

### ISSUE THREAD

**Issue by SamKrish1405** [MCMrARM/mc-w10-version-launcher#115]
I can install all other versions and launch it too but this problem happens only for 1.17 I thought that because it just released it might take some time but after a day also its not launching I also tried reinstalling it several times but still no  luck with launching.

Please help me Ive been waiting for almost a year for the update to release and now I cant even play it .
![image_2021-06-09_152306](https://user-images.githubusercontent.com/68858201/121333615-97f89600-c936-11eb-8965-f2a068aca9de.png)

**Comment by tgxadi** [comment]
try re install the game through microsoft store
