### ISSUE TITLE
Bad Update Identity Issue

### ISSUE THREAD

**Issue by FreezzeYT** [MCMrARM/mc-w10-version-launcher#121]
As you have said in other Badidentity Isuue , the problem is not with only Beta , but also for Full versionssss

The problem still occurs with Full Release Versionssss

**Comment by FreezzeYT** [comment]
I can't Download any versions from MC Launcher

**Comment by 3dcoolcat** [comment]
I am having this same problem where when I try to download a version it is unable to download
