### ISSUE TITLE
Not recognizing the Insider Hub Program for Beta builds

### ISSUE THREAD

**Issue by Saki-Myoto** [MCMrARM/mc-w10-version-launcher#122]
I keep getting an error message saying that I need to subscribe to the Beta Program even though I already am. How long does it take for the launcher to recognize that the user is in the Beta Program?

**Comment by kimonxx** [comment]
I can confirm the issue

![grafik](https://user-images.githubusercontent.com/81018945/126036069-c6d0a424-d0e8-4cc5-b563-72586e5586d9.png)

**Comment by Startive** [comment]
had the same problem, i hope they fix it soon as my friend is on console and he has an older version of beta and he cant update to the newest version.
![image](https://user-images.githubusercontent.com/90710922/133289824-2662905e-964c-489a-82b7-9f6b0fc545c5.png)

**Comment by dktapps** [comment]
Y'all are using outdated versions.
