### ISSUE TITLE
How do I move minecraft from desktop/MCLauncher/1.17.2.1 back to the default location?

### ISSUE THREAD

**Issue by LanternServer** [MCMrARM/mc-w10-version-launcher#126]
Pretty much what the title says.. I want Minecraft to be back in it's default place because it's causing problems having it in MCLauncher.. Please help!! ):

**Comment by dktapps** [comment]
Uninstall all versions installed by MCLauncher. Once you've done that, you should be able to install MC using Microsoft Store.

**Comment by LanternServer** [comment]
Won't I lose everything then? Thanks for the quick reply btw

**Comment by dktapps** [comment]
Uninstalling via MCLauncher won't delete your worlds, if that's what you're asking.
