### ISSUE TITLE
Launcher does not work properly

### ISSUE THREAD

**Issue by DrAv0011** [MCMrARM/mc-w10-version-launcher#13]
Since some time the Launcher does not work properly, is not able to launch installed versions, cannot download betas (even when removed all Minecraft data and reinstalled, and when being in the beta insider program). Need to manually open appx files to make game work and more.
![image](https://user-images.githubusercontent.com/43525295/64062814-fafabc00-cbeb-11e9-8c74-6732ddc286d4.png)

**Comment by xJawzii** [comment]
same for me. i hope this gets patched soon.

**Comment by SuperAdam47** [comment]
![Ekran Alıntısı](https://user-images.githubusercontent.com/16169771/69010755-c2a98500-0973-11ea-8477-392bf9486303.PNG)
needs Fix

**Comment by AdrianCert** [comment]
I solve this problem:
In the root dir, I found a  `.Appx` file and I run it and all was fine

**Comment by jowi3** [comment]
Running .appx is not a fix. It just lets you install the app normally. You still won't be able to launch it from the launcher and MS Store will still try to update the game. Here's the steps that fixed my problem:

1-Go to >Windows settings>Update&Security>For Developers>
2-Choose/Enable "Developer Mode" from the list under "For Developers". Then scroll down and click on both of the "Apply" buttons under Windows Explorer and Powershell
3-Uninstall Minecraft
4-Open CMD with admin privilages
5-Write "powershell" and hit enter
6-Write "Get-AppxPackage -allusers *minecraftUWP* | remove-appxpackage -allusers" and hit enter

Done. Now you can open the launcher and download/launch as you like.

**Comment by dktapps** [comment]
This is fixed in the current master branch.
