### ISSUE TITLE
List not updating after importing a new version

### ISSUE THREAD

**Issue by stirante** [MCMrARM/mc-w10-version-launcher#131]
After importing a new version, I need to uncheck and check again the checkbox, that shows only installed versions, to see imported one.

Version: 0.2.1 (current latest release)
OS: Windows 11 (I doubt that would make a difference, but who knows)

As a side note, I'd love to have some icon for the launcher, just so it doesn't have that default app icon.

**Comment by dktapps** [comment]
Imported versions show up right at the bottom. I know it's not the best placement ...

**Comment by stirante** [comment]
Yes, but I have checked the checkbox, that shows only installed versions. After importing with this checkbox, no new version appears. I need to recheck the checkbox in order to see new version.

**Comment by dktapps** [comment]
Ah, I was a little unclear on the problem. I see what you mean and I'm able to reproduce it.

**Comment by stirante** [comment]
Wow, thanks! Gotta say, A+ response time
