### ISSUE TITLE
This program does not work

### ISSUE THREAD

**Issue by Veitaserum4** [MCMrARM/mc-w10-version-launcher#132]
It simply does not work at all, i either get errors, or no messages at all. it does not launch at all.

**Comment by dktapps** [comment]
![image](https://user-images.githubusercontent.com/14214667/125835789-eae81e1e-981f-448e-b544-971f0dd2d33c.png)

**Comment by T0m1sAnimz** [comment]
how can u launch it without MCLauncher.exe?
