### ISSUE TITLE
App re-register failed

### ISSUE THREAD

**Issue by CroppedRubbish** [MCMrARM/mc-w10-version-launcher#136]
I got the MCBE launcher and I decided to go all the way back to 0.14 beta. It downloads, and I click play, and it's about to load. Then I get the 'App re-register failed' error. I saw something saying to uninstall the actual MCBE, so I did. It still doesn't work. How do I fix this?!??!?.!?!>?>!?!

**Comment by gothgmgrrd** [comment]
I have the same problem

**Comment by MrManFace** [comment]
Try Another Version Of MCLauncer not 0.20

**Comment by MrManFace** [comment]
May work

**Comment by TheGamer308** [comment]
did it work for you

**Comment by CroppedRubbish** [comment]
I tried the 0.1.0 launcher, it didn't work. The versions come up, but when I go to download 0.14.0 it doesn't work. I was able to successfully download another version (1.0.0.16), but I got the App re-register failed again when trying to launch that.

**Comment by Robertyox** [comment]
i have the same problem.
but why ?

**Comment by Jochem-agro** [comment]
For people experiencing the same problem: I fixed this by turning on developer mode on my pc (you'll might need admin rights for this) 
![image](https://user-images.githubusercontent.com/61137869/134653172-8e6a4892-99d2-4c17-a60d-20e5ab54c197.png)
