### ISSUE TITLE
can't import

### ISSUE THREAD

**Issue by D33274D7C6** [MCMrARM/mc-w10-version-launcher#137]
Importing Microsoft's official installation package cannot be opened
![5G {1L`TI)@YBSH %_TH0WC](https://user-images.githubusercontent.com/85822722/128011992-dfcd821f-7a58-48f7-afd2-ffbf0a531b97.png)

**Comment by cycode0527** [comment]
I have the same problem,but why it have Chinese?(I'm Chinese)

**Comment by D33274D7C6** [comment]
I'm sorry, I forget delet "AppxSignature.p7x"

**Comment by D33274D7C6** [comment]
> 
> 
> 导入微软官方安装包打不开
> ![5G {1L`TI) @YBSH% _TH0WC](https://user-images.githubusercontent.com/85822722/128011992-dfcd821f-7a58-48f7-afd2-ffbf0a531b97.png)



> 
> 
> 导入微软官方安装包打不开
> ![5G {1L`TI) @YBSH% _TH0WC](https://user-images.githubusercontent.com/85822722/128011992-dfcd821f-7a58-48f7-afd2-ffbf0a531b97.png)

I'm sorry, I forget delet "AppxSignature.p7x"

**Comment by D33274D7C6** [comment]
> 
> 
> I have the same problem,but why it have Chinese?(I'm Chinese)

你是中国用户？

**Comment by cycode0527** [comment]
> > I have the same problem,but why it have Chinese?(I'm Chinese)
> 
> 你是中国用户？

是的，但是我看错了，我的好像不是这个问题（或说导入有什么用）

**Comment by cycode0527** [comment]
> > I have the same problem,but why it have Chinese?(I'm Chinese)
> 
> 你是中国用户？

是的，但是我看错了，我的好像不是这个问题（或说导入有什么用）

**Comment by D33274D7C6** [comment]
> > > I have the same problem,but why it have Chinese?(I'm Chinese)
> > 
> > 
> > 你是中国用户？
> 
> 是的，但是我看错了，我的好像不是这个问题（或说导入有什么用）

用处很大，MClauncher不支持下载x86的win10MC，但是可以通过导入使用x86Minecraft。
OJANG更新新光影引擎导致原来的光影无法使用，但是给x86MC留了一条生路。

**Comment by D33274D7C6** [comment]
问题已解决
problem solved.
