### ISSUE TITLE
Can't download versions below 0.14.0.1

### ISSUE THREAD

**Issue by Mc-muffin** [MCMrARM/mc-w10-version-launcher#14]
First of all, thank you for doing this, I always wanted a version history for Win10 edition.

Now, for the issue when downloading any 0.13.x version the "Bad updateIdentity" message comes up, just to be clear I can download every other version (including betas) I'm just wondering why I can't test the oldest available version.

Also, as a side question, how does this program works? I thought you couldn't download older apps from the Microsoft Store

**Comment by dktapps** [comment]
As written elsewhere, the older versions are provided as-is, they may or may not work. The IDs for these versions were recovered manually from older PCs which had those versions installed.
