### ISSUE TITLE
App sound volume resets every time you launch the app

### ISSUE THREAD

**Issue by thebigsmileXD** [MCMrARM/mc-w10-version-launcher#140]
This might be due to a windows bug, but it is still strange - other sideloaded appx packages do not have that issue for me.

**Comment by dktapps** [comment]
It's not a bug, it's due to the way the launcher works. Every time you launch, the package is essentially getting reinstalled. This is unavoidable.

**Comment by thebigsmileXD** [comment]
As of my understanding, it is only getting reinstalled when you click "launch" in the launcher, not when you start Minecraft via shortcut
