### ISSUE TITLE
can't Launch

### ISSUE THREAD

**Issue by akrd1337** [MCMrARM/mc-w10-version-launcher#147]
Can't Launch :( 
![image](https://user-images.githubusercontent.com/91388321/134781486-d7e3aace-4dab-4b36-847a-2b40026336df.png)
-This developer mode-

![image](https://user-images.githubusercontent.com/91388321/134781508-44ec464f-64e1-4abd-8605-6eb963fbd8fe.png)
-This error-
:(

**Comment by githubsucksfr** [comment]
same thing happens to me

**Comment by martin-gw** [comment]
Try deleting the game and its folders in Appdata, and then restart the computer, it worked for me ...

**Comment by dktapps** [comment]
Update to the latest version.
