### ISSUE TITLE
Missing visual studio runtime files?

### ISSUE THREAD

**Issue by njt1982** [MCMrARM/mc-w10-version-launcher#156]
![F3BFA1C6-7A36-44B6-8EE1-262F5D27F5C4](https://user-images.githubusercontent.com/384976/143685507-afa8fccc-4e04-4ea6-ad87-c20d7af534a2.jpeg)

im getting this error (along with several other similar errors).

I have developer mode on.

I have uninstalled and reinstalled the latest vcc redistributable for x86 and x64.

Minecraft is running as an admin account.

I’ve tried copying the 4 files into the folder; no effect.

I get the same error on latest 1.17 and 1.18 downloads.

I have tried deleting and re-downloading.

what am I missing? Anything else I can try?

**Comment by dktapps** [comment]
Try installing the appx manually and then run versions from the launcher after. The launcher is currently missing some game dependencies.

**Comment by njt1982** [comment]
Latest build seemed to fix this...

**Comment by dktapps** [comment]
I didn't change anything related to this so it's probably just a coincidence.
