### ISSUE TITLE
wont open

### ISSUE THREAD

**Issue by SSapphire666** [MCMrARM/mc-w10-version-launcher#161]
![Screenshot 2021-12-04 091928](https://user-images.githubusercontent.com/95534780/144712921-721cfea5-3f9b-4649-a4ef-1ad9210c8fdc.png)
dont know how to do this

**Comment by njt1982** [comment]
When that happens it should also open an explorer to the path of the tmp backup. You could rename / zip up / remove that folder as needed.

**Comment by dktapps** [comment]
Duplicate of #103
