### ISSUE TITLE
Latest Betas missing from version list.

### ISSUE THREAD

**Issue by sccsltd** [MCMrARM/mc-w10-version-launcher#169]
Last entries in versions list
["1.18.10.20","46ac4b44-2ee4-430c-b367-d91544bd44cb",1],["1.18.10.21","8eb5cf27-160e-42db-bd8c-f010492cfb03",1]]

we should have 2 new beta versions

Minecraft Beta - 1.18.10.26 (Xbox / Windows / Android) 8a96ef50-d4d7-42af-8d52-b4e895cefc85
Minecraft Beta - 1.18.10.24 (Xbox / Windows / Android)

**Comment by moe41** [comment]
![無題](https://user-images.githubusercontent.com/66813644/148636086-1ebce320-1f8a-4a88-9448-186969ef5cea.png)
but now, only 1.18.10.24 isn't in version list.

**Comment by dktapps** [comment]
There's not much that can be done about that. The bot that scrapes the versions had an outage. It grabbed the most recent ones when it came back online, but it can't fetch older ones.
