### ISSUE TITLE
preview version

### ISSUE THREAD

**Issue by moe41** [MCMrARM/mc-w10-version-launcher#177]
![無題](https://user-images.githubusercontent.com/66813644/153449111-09e3734c-8e93-4b52-857f-69e075fcdcb0.png)
1.18.20.26 is preview version
i think better to separate preview version

**Comment by MCMrARM** [comment]
This is being worked on: https://github.com/MCMrARM/mc-w10-version-launcher/pull/175

**Comment by dktapps** [comment]
This is a bug in current versions of the launcher due to this code: https://github.com/MCMrARM/mc-w10-version-launcher/blob/master/MCLauncher/VersionList.cs#L52

`Preview` uses type 2, which is not equal to 1, which makes the launcher think it's a release.
