### ISSUE TITLE
Installed Versions

### ISSUE THREAD

**Issue by Fyeeee** [MCMrARM/mc-w10-version-launcher#178]
Well, I've installed a version and I want to create some Add-ons so, I need the folder with the version that I've download. But, it's seems to be nowhere and it doesn't exist... I can' find it anywere,, can you help me ?

**Comment by dktapps** [comment]
File -> Open launcher data folder

**Comment by Fyeeee** [comment]
in McLauncher file i only have: MClauncher.exe, MCLauncher.pdb, Newtonsoft.Json.dll, Newtonsoft.Json.pdb, WUTokenHelper.dll, WUTokenHelper.pdb and nothing more...
