### ISSUE TITLE
help i have this error after open the game

### ISSUE THREAD

**Issue by moha123579** [MCMrARM/mc-w10-version-launcher#182]
![image](https://user-images.githubusercontent.com/92060895/154808509-86b00e0e-830f-43ea-a031-16f995f94742.png)

**Comment by zlanc** [comment]
idk I have a similar problem, try deleting it from the install location. BUT if you dont want to lose all your worlds then idk

**Comment by dktapps** [comment]
The recommended approach is to install the app from the Microsoft Store, and then use the launcher to overwrite it. Doing a clean install using the launcher only likely won't work correctly due to dependencies which the launcher doesn't know to install.
