### ISSUE TITLE
Question: How do you exactly fetch the version list for MC Bedrock? (Or any UWP App in general?)

### ISSUE THREAD

**Issue by Aetopia** [MCMrARM/mc-w10-version-launcher#188]
As the title suggests, I am want to know how one can exactly interact with the MS Store servers to get a uwp's version list and download links?

**Comment by DelofJ** [comment]
Here you have everything you need to know, you have the link in the comments to find the IDs to make the script work also available in the comments, there is also a guy who put a link there that tells how to make the script work https://github.com/MCMrARM/mc-w10-version-launcher/issues/114
