### ISSUE TITLE
'Download failed' error when try to download minecraft version 1.14.0.51

### ISSUE THREAD

**Issue by ASOwnerYT** [MCMrARM/mc-w10-version-launcher#19]
![image](https://user-images.githubusercontent.com/23545044/69893935-4f454180-137d-11ea-92e6-51797decdb20.png)

**Comment by ASOwnerYT** [comment]
Sorry I had to take a screenshot it wont let me copy and paste

**Comment by THEJaxster** [comment]
Is the updating to the new versions broken.  The new 1.14 update does not show up.
