### ISSUE TITLE
Missing Versions

### ISSUE THREAD

**Issue by Mario60866iPod13** [MCMrARM/mc-w10-version-launcher#190]
I really like this app! But, there are a few versions of the game missing.

First, 0.13.x won't download due to an error.

Also, 0.12.x versions are missing.

Thanks ahead of time for fixing this.

**Comment by Xivaskk** [comment]
fds

**Comment by dktapps** [comment]
Unfortunately there's nothing we can do about this. Older versions are provided on a best-effort basis, and their availability depends on Microsoft's internal servers, so versions might stop being available at any time.
