### ISSUE TITLE
Pre register issue

### ISSUE THREAD

**Issue by Istealbits** [MCMrARM/mc-w10-version-launcher#195]
![helppls](https://user-images.githubusercontent.com/104109122/164340573-420dee3a-282a-4ee4-89df-ea1ebde2bee6.png)
Aight i tried everything including the checking the thing for installed minecraft without me seeing it or smth
i have java edition for additional info but yeah idk, i was trying to run a version from before like literally one update ago you can see the version on the top of the screenshot
 if anyone could help or wanna go further with helping me i'll drop my discord rq
StealingBits#7299

**Comment by Hamster003** [comment]
this happens to me as well

**Comment by epicstente** [comment]
Hi

I had the exact same problem and solved it by turning on "Developer mode" in windows :)

Refering to this issue :)
https://github.com/MCMrARM/mc-w10-version-launcher/issues/184#issue-1158740167

GL HF

**Comment by Hamster003** [comment]
> Hi
> 
> I had the exact same problem and solved it by turning on "Developer mode" in windows :)
> 
> Refering to this issue :) [#184 (comment)](https://github.com/MCMrARM/mc-w10-version-launcher/issues/184#issue-1158740167)
> 
> GL HF

I have developer mode on
