### ISSUE TITLE
How it works?

### ISSUE THREAD

**Issue by Lind0f** [MCMrARM/mc-w10-version-launcher#2]
1. I downloaded and launched the program.
2. Removed the installed game and downloaded the new version.
3. When i press the launch button, nothing happens.

**Comment by Lind0f** [comment]
`Download start
Resolved download link: http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/63d7876f-f2fa-4927-b35e-909a0b80a2cb?P1=1553449462&P2=402&P3=2&P4=OdsxVT02kxrXcqDUDB7XerXeZ0sFLr53gFwkooBEJTyhCYPZZrWWEZ7URRx%2bGXhIBBxFH9Wx%2b3kXiVpI%2fvAokg%3d%3d
Actual download started
Download complete
Registering package
Deployment done: Error
App re-register done!
App launch finished!
Registering package
Deployment done: Error
App re-register done!
App launch finished!
Registering package
Deployment done: Error
App re-register done!
App launch finished!
Registering package`

**Comment by abc-55** [comment]
Did you enable developer mode in windows settings?
