### ISSUE TITLE
App re-register failed:

### ISSUE THREAD

**Issue by tenistia** [MCMrARM/mc-w10-version-launcher#203]
System.Exception: Deployment failed: Deployment of package Microsoft.MinecraftUWP_1.18.3004.0_x69_(random string of numbers and letters) with package origin Unsigned failed because no valid license or sideloading policy could be applied. blah blah blah error thingie

also one of the parts in this long error said: C:\Users\dylan-work\Documents\projects\mcw10 whatever there is. I am pretty sure I am not dylan. some other guy who is related to this project might be.

**Comment by Dan-k391** [comment]
same

**Comment by LFC6times** [comment]
You need to enable developer mode in Windows Settings (as stated in release 0.10). Go to Windows settings, then Update & Security, and the second from the bottom on the sidebar should be "For developers". Hop in there and enable developer mode.

**Comment by EgDroneMind** [comment]
I have it enabled, though if I were to guess I think the cause of this error is the fact that java and bedrock are now in a bundle in the Microsoft store

**Comment by EgDroneMind** [comment]
> You need to enable developer mode in Windows Settings (as stated in release 0.10). Go to Windows settings, then Update & Security, and the second from the bottom on the sidebar should be "For developers". Hop in there and enable developer mode.

I have it enabled, though if I were to guess I think the cause of this error is the fact that java and bedrock are now in a bundle in the Microsoft store

**Comment by ktbloomq** [comment]
I also have this issue

**Comment by its-hijack** [comment]
Is there any news on patches for this issue, i investigated further and it appears that it is unable to properly verify which may be due to the new Minecraft Launcher transition. Will there be another update to the launcher to patch this issue? As this is a serious issue effecting functionality of the launcher. 

Can confirm that this issue is also not caused by lack of VS or Developer mode.

**Comment by AHHHHIMMAAD** [comment]
install appx first then delete it and lauch the extracted one and your gud to go

**Comment by lucaciuc** [comment]
> install appx first then delete it and lauch the extracted one and your gud to go

I dont understand bruh...

**Comment by Benjib0y** [comment]
I get this error too.
Windows update says my system is up to date.
My OS is Win10 version 21H2. OS Build 19044.1889. The m/c is an N3350 X64.
Any ideas?
