### ISSUE TITLE
no 1.19.2

### ISSUE THREAD

**Issue by NoSkillPureAndy** [MCMrARM/mc-w10-version-launcher#207]
1.19.2 is missing

**Comment by NoSkillPureAndy** [comment]
![image](https://user-images.githubusercontent.com/72871450/175125015-e680662f-fc72-4f88-8440-1a5023e8dbb8.png)

**Comment by kimonxx** [comment]
Latest Preview - I think 1.19.10.23? - is missing as well :(

**Comment by kimonxx** [comment]
It works again! Just downloaded 1.19.2.2 and Preview 1.19.10.24. Thanks for the quick fix
