### ISSUE TITLE
a way to bypass "app re-register failed" error on older version of windows

### ISSUE THREAD

**Issue by GDjkhp** [MCMrARM/mc-w10-version-launcher#212]
this thing pops up, is there a way to force-install on old win10 version? or should i update the system instead...

![image](https://user-images.githubusercontent.com/51813377/178767520-e26b1129-a2f2-4b86-a41c-a7534244992f.png)

**Comment by CyberSteve777** [comment]
Looks like you need to update WIndows

**Comment by GDjkhp** [comment]
> Looks like you need to update WIndows

ye, this might be the only solution that i can think of…

**Comment by Benjib0y** [comment]
I get this error too. 
Windows update says my system is up to date.
My OS is Win10 version 21H2. OS Build 19044.1889.  The m/c is an N3350 X64.
Any ideas?
