### ISSUE TITLE
When I try to launch an imported appx it says that I don't have a high enough version

### ISSUE THREAD

**Issue by HarryFOOTFOOT** [MCMrARM/mc-w10-version-launcher#214]
![mclauncher error](https://user-images.githubusercontent.com/81161117/180647181-dcd27038-f1e1-4e14-a23c-a96a3915576d.png)

**Comment by HarryFOOTFOOT** [comment]
why was this closed?

**Comment by dktapps** [comment]
the error tells you what the problem is
