### ISSUE TITLE
APPX Deleting

### ISSUE THREAD

**Issue by Saksh2022** [MCMrARM/mc-w10-version-launcher#225]
When I install 1.19.31. And game starts extracting. After extracting the APPX automatically gets deleted. When installing it is there, But after extracting it disappears. In log.txt it shows Deleting APPX to reduce disk usage,

**Comment by GreatNate0509YT** [comment]
Close this issue

**Comment by Saksh2022** [comment]
Dude
But where can I switch it off?

**Comment by Saksh2022** [comment]
@GreatNate0509YT

**Comment by GreatNate0509YT** [comment]
Clock options and then click the delete appx after download to save space make sure it doesn’t have a check mark if it still happens idk what to tell u
