### ISSUE TITLE
App re-register failed

### ISSUE THREAD

**Issue by dropalways** [MCMrARM/mc-w10-version-launcher#228]
![YtdGb2cDIZ](https://user-images.githubusercontent.com/120043514/206236271-7e49d44a-afc5-4b31-a237-18173d6cfc9d.png)

**Comment by dropalways** [comment]
> 2\. o

Yes i do
No i did not

**Comment by Schwerthecht** [comment]
i got the same problem, also with developer mode activated, no beta or preview version

**Comment by Schwerthecht** [comment]
![image](https://user-images.githubusercontent.com/90722328/210141199-ed7304db-da3b-442c-b33e-afad7e05fc91.png)
that's what the error looks like for me (sry for german)

**Comment by bspdeveloper** [comment]
I also have the same problem

**Comment by KristOFF-T** [comment]
I also have the same problem.

**Comment by bspdeveloper** [comment]
Hey Everyone, This problem is occuring because you people are trying to install it without actually owning it.
You cant crack Minecraft with this
Thank You

**Comment by Schwerthecht** [comment]
ah ok, thy! i have a legit minecraft account, but somehoe my store/normal mc launcher isn't letting me install minecraft bedrock edition. Is there a way to install via this, but launch via the nornal launcher?

**Comment by loneneuron** [comment]
Would be nice to at least see the demo working.

**Comment by miqumi** [comment]
https://github.com/MCMrARM/mc-w10-version-launcher/issues/246
