### ISSUE TITLE
Access denied

### ISSUE THREAD

**Issue by Laith98Dev** [MCMrARM/mc-w10-version-launcher#230]
When i launch it
[Log.txt](https://github.com/MCMrARM/mc-w10-version-launcher/files/10271956/Log.txt)
![image](https://user-images.githubusercontent.com/49840784/208754049-c2e96b8d-fa1c-4d41-ac9b-0aa2d0f10c23.png)

**Comment by GreatNate0509YT** [comment]
Ru

**Comment by GreatNateDev** [comment]
Try launching it as admin

**Comment by Laith98Dev** [comment]
didn't work, anyway i'm using v2 now and it works fine
