### ISSUE TITLE
make it possible to download beta versions without xbox insider hub verification

### ISSUE THREAD

**Issue by lucaciuc** [MCMrARM/mc-w10-version-launcher#232]
![image](https://user-images.githubusercontent.com/85667418/209669104-1026ae3f-faeb-4d26-87b7-ff2f3651beaa.png)

**Comment by dktapps** [comment]
Beta downloads no longer work whether you're using Insider Hub or not. The tab will be removed in a future release.

**Comment by lucaciuc** [comment]
Then why are they still updating these versions?

**Comment by dktapps** [comment]
They aren't. The most recent one is 1.19.0, as you can see in your own screenshot.

**Comment by lucaciuc** [comment]
do you have this appx file?
