### ISSUE TITLE
App Re-gister Failed

### ISSUE THREAD

**Issue by JustWolter** [MCMrARM/mc-w10-version-launcher#241]
My Windows 11 is up to date
I have the latest drivers
GTX 1650
I7-9750H

![image](https://user-images.githubusercontent.com/83448525/217606152-a36be6e9-0598-43f1-8709-5ee98564227d.png)

**Comment by GreatNate0509YT** [comment]
Sign into Microsoft account that owns minecraft for windows make sure dev modes is on and make sure wifi is on

**Comment by netflexy** [comment]
where

**Comment by miqumi** [comment]
> Sign into Microsoft account that owns minecraft for windows make sure dev modes is on and make sure wifi is on

very helpful thank you very much bro

**Comment by miqumi** [comment]
> where

make sure to uninstall mc from ms store before installing using the launcher

**Comment by miqumi** [comment]
https://github.com/MCMrARM/mc-w10-version-launcher/issues/246
