### ISSUE TITLE
[Guide] App re-register failed Windows 10/11

### ISSUE THREAD

**Issue by TukangM** [MCMrARM/mc-w10-version-launcher#242]
if you get kinda same issue like this. try this medthod
![image](https://user-images.githubusercontent.com/91467886/220094466-85302ffa-6358-415f-b199-78cff42ad8be.png)
you are very lucky here!

1.turn on dev mode (pls turn on dev mode)
![image](https://user-images.githubusercontent.com/91467886/220094866-22b7830d-6e0a-4d9a-85e4-6db92bd7c0f3.png)
![image](https://user-images.githubusercontent.com/91467886/220095446-1ea04891-dc54-4c12-8e14-bd124eff48d9.png)

2. (not important) run powershell as administrator then paste this code `Set-ExecutionPolicy -ExecutionPolicy Unrestricted`. if asked type a to yes-to-all
![image](https://user-images.githubusercontent.com/91467886/220095284-1db1cb11-284c-4394-a69a-dfddbc9d5376.png)

![image](https://user-images.githubusercontent.com/91467886/220095126-aadaa1bc-ef1a-4a0b-a17c-2782d5837304.png)
 !warning! dont use powerhell black (powerhell black from github.com/microsoft / microsoft store lts / powershell msi package. use old powershell)

 3.try move `MC LAUNCHER`  from outside C: into C:\Program Files\ and try rename `MC LAUNCHER` into `mcl`
![image](https://user-images.githubusercontent.com/91467886/220095982-d6bb6d04-60e3-4cf0-ba07-e6f09dfc70a8.png)

 4.try launch `MCLauncher.exe` then download / (re)launch...
 ![image](https://user-images.githubusercontent.com/91467886/220096583-d9abe003-cf61-4a37-b0c1-2c95a46ed632.png)

 5.voila!!! get the minecraft launched!!
 ![image](https://user-images.githubusercontent.com/91467886/220096990-955cfd92-8cda-499f-944a-13712624294d.png)

**Comment by dktapps** [comment]
This application does not use powershell, there is no need to change execution policy. That's just making you vulnerable to malware.

**Comment by TukangM** [comment]
ok. i will update the guide >///<

**Comment by miqumi** [comment]
They still get it after enabling dev mode. The issue is that you have to uninstall minecraft from the store first.
Also if it still appears click on launch again.
(ALSO PLEASE REMOVE POINT 2>!!! it just makes your pc vulnerable to attacks and thats it.
https://github.com/MCMrARM/mc-w10-version-launcher/issues/246

**Comment by TukangM** [comment]
welp updated guide

**Comment by miqumi** [comment]
Covers everything. Great 👍🏻

> welp updated guide
