### ISSUE TITLE
1.19.73 not appearing

### ISSUE THREAD

**Issue by miqumi** [MCMrARM/mc-w10-version-launcher#247]
### Problem in 
 [versions.txt](https://github.com/MCMrARM/mc-w10-versiondb/blob/master/versions.txt#L3522) (Line 3522)
 [versions.json.min](https://github.com/MCMrARM/mc-w10-versiondb/blob/master/versions.json.min)
### Desc
 1.19.73 should be present but i s n ' t 
 (versions.txt: Line 3522 Col 1)
 (versions.json.min: Line 1 Col 15072)
### Possible solution
update the thing.

**Comment by dktapps** [comment]
Fixed

**Comment by miqumi** [comment]
![image](https://user-images.githubusercontent.com/80510430/229274466-bed6fcfb-7630-4c5f-81e3-6430a7bc379d.png)
![image](https://user-images.githubusercontent.com/80510430/229274489-75dff7fd-3f0a-4f64-97a0-2d66838505fb.png)
can you tell me a bit more about these bits of data next to the version number?

**Comment by miqumi** [comment]
n e v e r m i n d i g u e s s

**Comment by GreatNateDev** [comment]
Looks like a uuid to me 🤷

**Comment by miqumi** [comment]
> Looks like a uuid to me 🤷

my question was w h e r e t o o b t a i n
