### ISSUE TITLE
I18N support

### ISSUE THREAD

**Issue by lgc2333** [MCMrARM/mc-w10-version-launcher#249]
#197

**Comment by lgc2333** [comment]
zh-CN trans refererce https://github.com/Chlna6666/mc-w10-version-launcher

**Comment by miqumi** [comment]
???
VERY unnecessary.
i mean all of us can understand English
it would be an unnecessary implementation

**Comment by lgc2333** [comment]
> ??? VERY unnecessary. i mean all of us can understand English it would be an unnecessary implementation

i think not

**Comment by GreatNateDev** [comment]
I don't think it's unnecessary

**Comment by miqumi** [comment]
> > ??? VERY unnecessary. i mean all of us can understand English it would be an unnecessary implementation
> 
> i think not
> 
> lots of chinese people can not understand english 🙁

then they should learn english, 
there's a seperate version of Minecraft for China, 
and this is a really simple utility for a really small task, so it would be unnecessary effort.
I can make my own terminal based launcher with language support if you want to contribute.

**Comment by MCMrARM** [comment]
The launcher is indeed a rather simple project and there's not that many resources that can be used to improve it. I disagree with calling the feature unnecessary though - although it might not be high priority.

If a PR can be opened to properly support localization (WPF has APIs for it), I don't see why it wouldn't be merged.

**Comment by lgc2333** [comment]
> then they should learn english, there's a seperate version of Minecraft for China, and this is a really simple utility for a really small task, so it would be unnecessary effort. I can make my own terminal based launcher with language support if you want to contribute.

the chinese version of mc should be in the trush bin

**Comment by miqumi** [comment]
> > then they should learn english, there's a seperate version of Minecraft for China, and this is a really simple utility for a really small task, so it would be unnecessary effort. I can make my own terminal based launcher with language support if you want to contribute.
> 
> the chinese version of mc should be in the trush bin

sorry you win

**Comment by saturneimi** [comment]
i would like a localization feature!
any plans MrARM?
