### ISSUE TITLE
plz hlp mi ;(

### ISSUE THREAD

**Issue by raamvignesh** [MCMrARM/mc-w10-version-launcher#250]
When launcher is opened it is showing a blank screen plz help ;(     .
![Screenshot (95)](https://user-images.githubusercontent.com/129839513/229734031-4470e341-d3ee-497d-b85c-512b024f423c.png)

**Comment by GreatNateDev** [comment]
Wifi?

**Comment by miqumi** [comment]
bro click on release/Preview






ur blind ig

**Comment by aman200703** [comment]
i have same problems anyone got solutions?
or maybe alternatives

**Comment by aman200703** [comment]
![Capture](https://github.com/MCMrARM/mc-w10-version-launcher/assets/91415997/64c13d96-ec6a-4eae-841e-c2fdd29e60a6)
