### ISSUE TITLE
adding versions that are missing

### ISSUE THREAD

**Issue by bullfrogberry** [MCMrARM/mc-w10-version-launcher#26]
I wold like to be able to add more version options to the list manually. i tried editing "versions.json" using notepad text editor but came across two issues.
1. when i saved the file and relaunched the launcher the versions.json reverted back to the original.
2. I dont understand the conection between the MS Store Download APPX link which I already obtained and the number in relation to the version number in the "versions.json" file.

any help. I would like the insider Beta RTX 1.15.8.0 ... and future RTX betas in the feature.

**Comment by sprintermax** [comment]
Save the file as "read-only", it worked for me to download custom versions

**Comment by dktapps** [comment]
versions.json isn't supposed to be edited manually. It's just a local cache of this: https://mrarm.io/r/w10-vdb
