### ISSUE TITLE
Nothing happens on launch

### ISSUE THREAD

**Issue by Kai-Denzel-Jane** [MCMrARM/mc-w10-version-launcher#269]
Hey no longer getting app register issues but now after clicking launch nothinhs besides the log updates with this including the download part from log

Resolved download link: http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/f1256285-5f98-4cea-b9b2-1f1862f156cc?P1=1692362742&P2=404&P3=2&P4=nCaIo0s42z8weCXY4Lh3n7o%2fzHgvGe4sJryslaR%2b4se3C6kIhjYphApIfDjwVDRXctXpe0isSnZLXfs5W%2bxx0g%3d%3d
Actual download started
Download complete
Deleting APPX to reduce disk usage
Registering package
Deployment progress: Processing 1%
Deployment progress: Processing 2%
Deployment progress: Processing 49%
Deployment progress: Processing 51%
Deployment progress: Processing 98%
Deployment progress: Processing 98%
Deployment progress: Processing 100%
Deployment done: Completed
App re-register done!
App launch finished!
Skipping package removal - same path: Microsoft.MinecraftUWP_1.11.402.0_x64__8wekyb3d8bbwe C:\Program Files\mcl\Minecraft-1.11.4.2
App launch finished!
Skipping package removal - same path: Microsoft.MinecraftUWP_1.11.402.0_x64__8wekyb3d8bbwe C:\Program Files\mcl\Minecraft-1.11.4.2
App launch finished!

**Comment by DaxTheDerp** [comment]
download https://aka.ms/vs/16/release/vc_redist.x64.exe
