### ISSUE TITLE
cant use app-reregister fails

### ISSUE THREAD

**Issue by xAffan** [MCMrARM/mc-w10-version-launcher#27]
whenever I try to launch mc win10 with the launcher it says app-re register failed
system cant find the file specified

**Comment by xAffan** [comment]
I did uninstall minecraft before, but some files were still there in WindowsApps folder, even after deleting that, the issue still persists

**Comment by xAffan** [comment]
https://ibb.co/F6K3S4G

**Comment by xAffan** [comment]
fixed. removed package for all users

**Comment by compiledsystem** [comment]
thanks

**Comment by Zux9993** [comment]
hi can you tell me how you did this please

**Comment by xAffan** [comment]
Actually on my PC, MC wasnt properly uninstalled. It was only uninstalled
for the current user but existed for some other user. So I somehow
uninstalled it properly, dont remember how
