### ISSUE TITLE
All 1.16 beta's not working.

### ISSUE THREAD

**Issue by ElTreago** [MCMrARM/mc-w10-version-launcher#29]
None of the 1.16 beta's can download through the version launcher, which is disappointing as they nerfed a lot of new features in 1.16.0.58 and we can only play the latest version. It would be great to be able to go back to .57.

![launcher](https://user-images.githubusercontent.com/64241956/80173477-570ac880-8633-11ea-9a48-f2512184b145.PNG)

**Comment by TrinityDevelopers** [comment]
This is due to the way MCLauncher handles accounts for beta versions. It simply chooses the first account it finds on your computer which may or may not be an account on the beta program.

**Comment by dktapps** [comment]
If that's true, it might be a good idea to have a UI to select an account when the launcher detects multiple accounts. @MCMrARM would this be doable?

**Comment by Cub53king** [comment]
Still cant download betas when i'm on the beta program.

**Comment by ElTreago** [comment]
@TrinityDevelopers thank you. I managed to fix it by signing in to the same microsoft account as my windows 10 account. However, now new beta's have stopped showing up in the version list. Any beta after .60 (.61, .63 etc.) won't come up.
