### ISSUE TITLE
lauching problem

### ISSUE THREAD

**Issue by Salve-o** [MCMrARM/mc-w10-version-launcher#295]
What to do when that message pops up and that window of the explorer open?
![Captura de tela 2024-04-04 150659](https://github.com/MCMrARM/mc-w10-version-launcher/assets/166057858/4d8108db-a635-4fd8-9c47-7ef3064797fc)

  That pops up when i click "ok".
![Captura de tela 2024-04-04 145549](https://github.com/MCMrARM/mc-w10-version-launcher/assets/166057858/c4144f4f-7d38-43ae-88c6-c4fae6c57cb0)
  And then it disappear when a click "ok" again

**Comment by DLazaridisGM** [comment]
i cant help dont have any experience with this error, but as it says you can back up The (TmpMinecraftLocalState) then delete it. again no experience just a suggestion

**Comment by Salve-o** [comment]
> Eu não posso ajudar não tenho qualquer experiência com este erro, mas como ele diz que você pode fazer backup O (TmpMinecraftLocalState) olhando para ele deve ter o seu mundo n coisas, em seguida, excluir a pasta que está em Appdata / Local. novamente nenhuma experiência apenas uma sugestão.
> 
> Encontrado estes #1 #161

**Comment by Salve-o** [comment]
> Eu não posso ajudar não tenho qualquer experiência com este erro, mas como ele diz que você pode fazer backup O (TmpMinecraftLocalState) olhando para ele deve ter o seu mundo n coisas, em seguida, excluir a pasta que está em Appdata / Local. novamente nenhuma experiência apenas uma sugestão.
> 
> Encontrado estes #1 #161

I  did #246 and it's worked.
