### ISSUE TITLE
no appx file 

### ISSUE THREAD

**Issue by UltraTapok223** [MCMrARM/mc-w10-version-launcher#312]
i just downloading minecraft 1.5.0 and when it ends i dont seeing appx file, only minecraft folder

**Comment by ChromiaCat** [comment]
> i just downloading minecraft 1.5.0 and when it ends i dont seeing appx file, only minecraft folder

Go into `preferences.json` and make sure it's false.

**Comment by UltraTapok223** [comment]
> > i just downloading minecraft 1.5.0 and when it ends i dont seeing appx file, only minecraft folder
> 
> Go into `preferences.json` and make sure it's false.

its still deletes
