### ISSUE TITLE
Don`t working

### ISSUE THREAD

**Issue by pelmen24** [MCMrARM/mc-w10-version-launcher#321]
I decided to download version 1.21.60.21 and the rest, I came across this problem, visual c++ is there, developer options are enabled.
![image](https://github.com/user-attachments/assets/51c00aff-2d89-4eed-8579-f7cfd52a4e9d)
![image](https://github.com/user-attachments/assets/ab636931-5438-49a9-98c4-9e28626c7d7b)
![image](https://github.com/user-attachments/assets/e0cb1f95-54ec-44bd-a538-b60b9212fe0a)
How can this be fixed?

**Comment by GreatNateDev** [comment]
are you signed in to the microsoft store with an account that owns minecraft bedrock?

**Comment by zal5oy** [comment]
i have the same error, dev roods are enabled and microsoft store account the same in minecraft

**Comment by zal5oy** [comment]
also i have this error
![Снимок экрана 2024-12-09 000620](https://github.com/user-attachments/assets/ad4a8161-fb9d-48ff-86ab-01c02a086652)

**Comment by pelmen24** [comment]
all fixed on version 4 of the launcher, bedrock minecraft i have. Even works on version 11 of windows
