### ISSUE TITLE
New 1.16 betas past 1.16.0.60 are not coming up

### ISSUE THREAD

**Issue by ElTreago** [MCMrARM/mc-w10-version-launcher#37]
I managed to fix the problem with downloading betas, however now new betas aren't showing up. The most recent is .63 and also .61 but wont show anything later than .60
![image](https://user-images.githubusercontent.com/64241956/82857164-8a52b700-9f53-11ea-9a37-455379f0ea52.png)

**Comment by CastOfficial** [comment]
Yep, same.

**Comment by ItzLightyHD** [comment]
This is because MCMrARM didn't update the versions.json file in his servers, so... we need to wait guys.

**Comment by adsvunu** [comment]
@MCMrARM do you have any date of when you're going to update the versions?
also if you provided how you get those versions we could make some pull requests with the versions

**Comment by McSkinnerOG** [comment]
I am currently making an updated list myself you will be able to to use if you build the source yourself for ALL his listed versions "he doesn't include some version for some reason"

**Comment by McSkinnerOG** [comment]
Here we are: https://pastebin.com/raw/Enk8sGNL

**Comment by ItzLightyHD** [comment]
> Here we are: https://pastebin.com/raw/Enk8sGNL

how did you find all the uuids?

**Comment by nasko222** [comment]
> Here we are: https://pastebin.com/raw/Enk8sGNL

yes how did you find those uuids??? I want for 0.12.0 because its the only version you can get legit nether reactor. Please i need help!

**Comment by THEJaxster** [comment]
> Here we are: https://pastebin.com/raw/Enk8sGNL

Hello, do you have the information for the latest release? 1.16?  Thanks

**Comment by McSkinnerOG** [comment]
GUYS i fixed it.
https://github.com/MCMrARM/mc-w10-version-launcher/pull/42

**Comment by dktapps** [comment]
If you haven't restarted the launcher recently, you should. The new versions will show up when you do.
