### ISSUE TITLE
How to Remove the launcher?

### ISSUE THREAD

**Issue by THEJaxster** [MCMrARM/mc-w10-version-launcher#38]
Hi.  I seem to be having problems and can't say it is the launcher nor do I want to blame it.  But for all purposes I need to move in and out of the betas and I have not been able to get in any of the 1.16.  I know you need the xbox insider hub to join them.  Setting all that aside.  How do I remove the launcher?  To be clear, I want to go back to the normal install process.  Thank you!

**Comment by dktapps** [comment]
Launch a PowerShell Administrator window and run this:
```ps
Get-AppxPackage -AllUsers Microsoft.MinecraftUWP | Remove-AppxPackage
```
(Note that -AllUsers is needed if the game is installed on multiple accounts.)
Then you should be able to install the game from the Store like you usually would.
