### ISSUE TITLE
Minecraft 1.16 full release isn't i list

### ISSUE THREAD

**Issue by shuluyo** [MCMrARM/mc-w10-version-launcher#39]
ı want to download minecraft 1.16 full release but this version isn't in list

**Comment by LukeGabriel1** [comment]
yes, i want too

**Comment by McSkinnerOG** [comment]
https://github.com/MCMrARM/mc-w10-version-launcher/pull/42 waiting for him to merge

**Comment by dktapps** [comment]
Already addressed several days ago.
