### ISSUE TITLE
Cannot launch any versions

### ISSUE THREAD

**Issue by Endermanbugzjfc** [MCMrARM/mc-w10-version-launcher#41]
I tried to use the method on YouTube to fix the 0x80070002 error but it still gave me this error.
![image](https://user-images.githubusercontent.com/53002741/85658463-dc6b3180-b6e5-11ea-9d70-be3f7bcca84d.png)

**Comment by Endermanbugzjfc** [comment]
> If you have VS, try building the latest master build instead of using the release.

k ty ill try

**Comment by Endermanbugzjfc** [comment]
> If you have VS, try building the latest master build instead of using the release.

@dktapps I tried to build it but this error occurred. Any solution, please?
![image](https://user-images.githubusercontent.com/53002741/85746308-f08c4e80-b738-11ea-84df-241332861d97.png)

**Comment by dktapps** [comment]
Select x64 instead of Any CPU.

**Comment by THEJaxster** [comment]
@Endermanbugzjfc , did you have any luck with the build?  and if so, does it work?

**Comment by 12brendon34** [comment]
this happens to me somtimes its probly because he has the origanal still installed and normaly thats not a problem but somtimes it happens so all you need to do is back up your game data uninstall minecraft then launch it from the version launcher

**Comment by dktapps** [comment]
It's nothing to do with that. It's caused by older versions of the launcher not properly unregistering packages when switching versions.

**Comment by ehamawy** [comment]
Can confirm building from source fixes the error. Now the game crashes on server join lol (1.16.x and 1.14.x)

**Comment by ehamawy** [comment]
Can confirm building from source fixes the error

**Comment by dotalottroller** [comment]
i am having the same issue but I'm not sure how to build from source, can you explain?

**Comment by Endermanbugzjfc** [comment]
> i am having the same issue but I'm not sure how to build from source, can you explain?

Download the Visual Studio and get errors on build, that's easy, isn't it?

**Comment by truaddict** [comment]
compiled from source, removed original version (from ms store). Still have the error.
