### ISSUE TITLE
Windows 10 edition beta 0.12.0 isn't on the list

### ISSUE THREAD

**Issue by nasko222** [MCMrARM/mc-w10-version-launcher#47]
Its the version that have nether reactor before its removed so i really need it, Can you add it on the list please if possible?

**Comment by dktapps** [comment]
The nether reactor was removed before 0.12.0...

**Comment by nasko222** [comment]
No, nether reactor was removed to be craftable and functionable in 0.12.1

**Comment by dktapps** [comment]
As I've written elsewhere, the older versions are provided as-is on a best effort basis. The IDs needed to download these versions are not readily available, so they had to be recovered manually from older PCs in the early days of the launcher. New releases are scraped and added automatically.

TL;DR: This isn't likely to be fixed.
