### ISSUE TITLE
How i use this program?

### ISSUE THREAD

**Issue by LGabriel2** [MCMrARM/mc-w10-version-launcher#49]
Help me, the download failed

**Comment by Todo56** [comment]
@LGabriel2 Go to https://github.com/MCMrARM/mc-w10-version-launcher/releases/tag/0.1.0, download the zip file, extract it and click on the .exe file. That will execute the launcher and the rest is quite intuitive. If you need anymore help you can checkout this video https://www.youtube.com/watch?v=5OiKDOakv1o
