### ISSUE TITLE
Cannot Launch Any Version

### ISSUE THREAD

**Issue by dotalottroller** [MCMrARM/mc-w10-version-launcher#51]
I am not able to launch any versions, and whenever i try then this error pops up:
![image](https://user-images.githubusercontent.com/68944161/89111028-b9a50900-d459-11ea-9058-2cfc1f18f65a.png)
I also went through the logs and after the download was completed, it says "App re-register failed:" followed by the text in the image

**Comment by dktapps** [comment]
https://github.com/MCMrARM/mc-w10-version-launcher#compiling-the-launcher-yourself

**Comment by AliBello** [comment]
I have that problem too. And I do not have enough storage to install it. Can someone please help me
