### ISSUE TITLE
Pls tell me how to download beta version, I want to downgrade to previous beta version to play with my friend but I can't know how to fix it

### ISSUE THREAD

**Issue by khanh3993** [MCMrARM/mc-w10-version-launcher#52]
![Screenshot (11)](https://user-images.githubusercontent.com/69384474/89706629-c1046f00-d991-11ea-8d42-fbcaac7b3df1.png)

**Comment by khanh3993** [comment]
Hey @MCMrARM, can you tell me how to fix it 😭, I'm 15 years old and I from Vietnam😁

**Comment by nasko222** [comment]
All of your Microsoft accounts connected in your Windows 10 PC need to have the beta program enabled in the Xbox insider hub.

**NOTE:** Xbox insider hub won't allow child accounts. If your account is assigned like this, you have to change it in the settings.
