### ISSUE TITLE
Every time I download a version this error comes up. How do I fix it? Or is anyone encountering the same thing?

### ISSUE THREAD

**Issue by treet123** [MCMrARM/mc-w10-version-launcher#55]
![image](https://user-images.githubusercontent.com/71253054/93056894-a6639b00-f69f-11ea-9704-96b4130eb0e6.png)

**Comment by chenxi050402** [comment]
Same problem.

**Comment by XXShippyx** [comment]
I also don't know what to do about it ...

**Comment by TacoNoBurrito** [comment]
you dont have developer mode enabled on your pc, you can enable it in your settings. Just lookup developer mode in the settings then goto use developer features  and click the developer mode circle, let it do its thing and then try to press launch again.

**Comment by Broody7678** [comment]
enable it, it works 100%
