### ISSUE TITLE
0.13.x versions do not work and 0.12.x versions aren't even there

### ISSUE THREAD

**Issue by mnuggdanugg** [MCMrARM/mc-w10-version-launcher#58]
i have no idea if the developers are still active but if anyone else knows what's up with it please tell me.
also if anyone has a 0.12.x appx that would be highly appreciated.

**Comment by leoghs** [comment]
if 0.13.x doesnt work then its a chance 0.12.x wont work either. maybe try getting 0.13.x versions to work before trying your hands at obtaining a 0.12.x appx.

**Comment by dktapps** [comment]
The oldest versions are provided on a best effort basis. They are present only because they were recovered manually from computers which previously had those versions installed. If those versions don't work, the chances of being able to salvage them are close to none.
