### ISSUE TITLE
Unknown error while downloading any version

### ISSUE THREAD

**Issue by XXShippyx** [MCMrARM/mc-w10-version-launcher#59]
When downloading any version from the launcher, the following error occurs:
![image](https://user-images.githubusercontent.com/73928070/98076575-b0806980-1e98-11eb-9238-b442b571b939.png)

**Comment by TacoNoBurrito** [comment]
you dont have developer mode enabled on your pc, you can enable it in your settings. Just lookup developer mode in the settings then goto use developer features  and click the developer mode circle, let it do its thing and then try to press launch again.

**Comment by Diyamund** [comment]
not working

**Comment by FrankHan052176** [comment]
> 您的电脑上未启用开发人员模式，您可以在设置中启用它。只需在设置中查找开发人员模式，然后使用开发人员功能并单击开发人员模式圈，让它做它的事情，然后尝试再次按下启动。

It does not work

**Comment by FrankHan052176** [comment]
you can not download the beta version.it is a bug.

**Comment by dktapps** [comment]
You need to subscribe to the beta program using Xbox Insider Hub to be able to download betas.
