### ISSUE TITLE
Do I reinstall minecraft?

### ISSUE THREAD

**Issue by SomeRandomGithub-User** [MCMrARM/mc-w10-version-launcher#62]
![image](https://user-images.githubusercontent.com/73361689/99869211-41dd2480-2b97-11eb-8c2f-4e48854fa7df.png)
I have played on 1.16.40 before so maybe its because of that

**Comment by leoghs** [comment]
strange. have you tried deleting the temporary directory with the files in it somewhere safe, if any?

**Comment by SomeRandomGithub-User** [comment]
> strange. have you tried deleting the temporary directory with the files in it somewhere safe, if any?

I already fixed it, I just had to delete Minecraft and install it again but thanks for helping
