### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by demureeeeee** [MCMrARM/mc-w10-version-launcher#63]
![image](https://user-images.githubusercontent.com/69711168/100427376-05c82900-309b-11eb-8492-abe3d95abcce.png)
![image](https://user-images.githubusercontent.com/69711168/100427388-09f44680-309b-11eb-9159-c4c165204832.png)

**Comment by demureeeeee** [comment]
dosent work when i installed and dragged them into the file

**Comment by dktapps** [comment]
You need to install Microsoft Visual C++ Redistributable. The 2015-2019 package should be sufficient.
