### ISSUE TITLE
MClauncher/Minecraft Microsoft store

### ISSUE THREAD

**Issue by DoDuK2** [MCMrARM/mc-w10-version-launcher#64]
Начало
загрузки Ошибка загрузки:
System.ArgumentException: недопустимый updateIdentity
в MCLauncher.VersionDownloader.d__6.MoveNext ()
--- Конец трассировки стека из предыдущего места, где было создано исключение ---
в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw ()
в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (задача задачи)
в MCLauncher.MainWindow. <> c__DisplayClass21_0. <b__1> d.MoveNext ()
when downloading Minecraft windows 10 edition from the Microsoft store, it gives an error "cannot install this application, try later" Minecraft was purchased and played before everything was fine, according to windows requirements, how to solve this problem? tell me I will be grateful.
Для русских :)))
при загрузке Minecraft windows 10 edition из Microsoft store выдает ошибку «не могу установить это приложение, попробуйте позже» Minecraft был куплен и играл до этого, всё было хорошо, windows соответствует с требованиями Minecraft, как решить эту проблему? скажиne, буду благодарен  :3

**Comment by IIWare** [comment]
Translation in english:
Start
download Download error:
System.ArgumentException: Invalid updateIdentity
at MCLauncher.VersionDownloader.d__6.MoveNext ()
--- End of the stack trace from the previous location where the exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw ()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (task task)
in MCLauncher.MainWindow. <> c__DisplayClass21_0. <b__1> d.MoveNext ()
when downloading Minecraft windows 10 edition from the Microsoft store, it gives an error "cannot install this application, try later" Minecraft was purchased and played before everything was fine, according to windows requirements, how to solve this problem? tell me I will be grateful.
For Russians :)))
when downloading Minecraft windows 10 edition from the Microsoft store, it gives an error "I can not install this application, please try later" Minecraft was purchased and played before, everything was fine, windows meets the requirements of Minecraft, how to solve this problem? tell me I will be grateful: 3

**Comment by dktapps** [comment]
If you want to download a beta, you need to join the beta program using Xbox Insider Hub.
