### ISSUE TITLE
1.16.201 not appearing in version list

### ISSUE THREAD

**Issue by devCarlton** [MCMrARM/mc-w10-version-launcher#67]
The new hotfix for Minecraft Bedrock has been out for a while now, and it hasn't appeared in my version list. Does this happen for everyone, or is it just me?

**Comment by Petrosado** [comment]
Yep happens to me too

**Comment by REALERvolker1** [comment]
This isn't really in active development, so it looks like we are stuck with 1.16.200.

**Comment by jared27906** [comment]
umm i dont know HOW but my minecraft suddenly updated to 1.16.201 IDK HOW

**Comment by dktapps** [comment]
good to know

**Comment by devCarlton** [comment]
Looks like .201 is appearing in the version list now, therefore I will be closing this issue.
