### ISSUE TITLE
Versions missing

### ISSUE THREAD

**Issue by Insistar** [MCMrARM/mc-w10-version-launcher#69]
I want to download the lastest stable version (1.16.201) but i cant find it , what do i do

**Comment by Xd-pro** [comment]
Bump!

**Comment by TwintailFD** [comment]
Please open the "versions.json" file and delete all the contents, then open "https://raw.githubusercontent.com/MCMrARM/mc-w10-versiondb/master/versions.json.min" and copy all the contents to this file. This will update the version list, but it only has .200 instead of version .201
