### ISSUE TITLE
Sorry, I violated your rights

### ISSUE THREAD

**Issue by nianxi4563** [MCMrARM/mc-w10-version-launcher#73]
I'm sorry! Since I have no copyright awareness, I uploaded the MClauncher application to my personal network disk without authorization, and then made a video to teach you how to use it, because I did not indicate the original author and the original github link, so I did it illegally , Now I have copyright awareness, I sincerely apologize to you, I have now deleted the link I uploaded, but the link is not spread in the video, just teach you how to use it, do I need to delete the video

**Comment by dktapps** [comment]
https://github.com/MCMrARM/mc-w10-version-launcher/blob/master/LICENSE.txt
