### ISSUE TITLE
mhm this pls help

### ISSUE THREAD

**Issue by quivzii-codez** [MCMrARM/mc-w10-version-launcher#76]
App installation failed with error message: Common::Deployment::MsixvcStagingSession::GetManifestReader in MsixvcStagingSession failed with error 0x80070570. (0x80070570)   

I get this can any1 help?

**Comment by DamianXAkuma** [comment]
i installed MCLAuncher and now my Minecraft Windows 10 is gone and i have to repay for it in the shop any help to fix this?

**Comment by slukky** [comment]
Any chance you found a fix 2 years later?
 Common::Deployment::MsixvcStagingSession::GetManifestReader in MsixvcStagingSession failed with error 0x80070570. (0x80070570)
