### ISSUE TITLE
It can't download in China!

### ISSUE THREAD

**Issue by WhatDamon** [MCMrARM/mc-w10-version-launcher#77]
I know I need a VPN, but I don’t know why I can only get the version list but not download it. It is recommended to change to an API. If you are the administrator of the API website and the website management tool used does not allow Chinese access, I suggest you find a better one. After all, there is a demand. If you can set to allow access to China, even if the download will be a little slower, it's no problem. Thanks.

**Comment by dktapps** [comment]
The list of versions is provided by GitHub and updated by MrARM's bot (https://github.com/MCMrARM/mc-w10-versiondb). The actual downloads are done directly from Microsoft's servers. If you have problems with the download, then you should use a VPN.

**Comment by WhatDamon** [comment]
I forked this project in Feb. 2023 and found it can fetch the database if i use the mirror instead of official one
Maybe it can provide a function that user can use the mirror if user cannot connect to the official link
In China, Github has been half banned by Great Firewall, i think that's the reason
