### ISSUE TITLE
Uninstall

### ISSUE THREAD

**Issue by waterdragon78** [MCMrARM/mc-w10-version-launcher#78]
How do I uninstall? I'm running out of storage and trying to install it on a USB, which the Microsoft store can do.

**Comment by lolpippiou** [comment]
If you want to put the launcher on your USB, move the folder with the launcher on the USB and that should work fine.

**Comment by DamianXAkuma** [comment]
i installed MCLAuncher and now my Minecraft Windows 10 is gone and i have to repay for it in the shop any help to fix this?

**Comment by lolpippiou** [comment]
That shouldn't be happening. It might be cause you got a virus.
