### ISSUE TITLE
minecraft isnt opening for me

### ISSUE THREAD

**Issue by YazdanPlug** [MCMrARM/mc-w10-version-launcher#83]
minecraft win 10 edition isn't opening for me. before update graphics card , minecraft java edition isn't opening for me. but i can opening mc win 10 edition. i updated my graphics card. now i can opening minecraft java edition. but i can't opening mc win 10 edition. its opned and show a red frame and closing

you can seeing red frame in the picture

i installed this in the microsoft store
![mcwinerror](https://user-images.githubusercontent.com/73750616/109415169-5ddd3700-79cc-11eb-8647-d6df1ba04118.png)
![mcwin10](https://user-images.githubusercontent.com/73750616/109415175-67669f00-79cc-11eb-9c2d-44e62f2a0d22.png)

**Comment by RealTriassic** [comment]
Same issue here.

**Comment by dktapps** [comment]
This is fixed in 0.2.0.
