### ISSUE TITLE
Can't download 0.13 version

### ISSUE THREAD

**Issue by Hillionliat** [MCMrARM/mc-w10-version-launcher#88]
I am downloading all versions for archiving succeeded in downloading every version except first three 0.13 is this because the files were deleted on Microsoft server if so does anyone have a backup

**Comment by ShyElephant** [comment]
no sorry

**Comment by ShyElephant** [comment]
hey can u help me i dont know where the exe is can u send me a copy

**Comment by dktapps** [comment]
Duplicate of #58
