### ISSUE TITLE
Wheres the exe i downloaded the file but theres no exe in sight i also watched foaxysnotails vid but that didt help

### ISSUE THREAD

**Issue by ShyElephant** [MCMrARM/mc-w10-version-launcher#89]

**Comment by ShyElephant** [comment]
plz help me

**Comment by dktapps** [comment]
![image](https://user-images.githubusercontent.com/14214667/112385926-1c4c5d00-8ce8-11eb-80a0-838630100407.png)

**Comment by slawrie25** [comment]
Did you unzip the .zip file? the .exe file is in there
