### ISSUE TITLE
compressed app package deleted upon extraction into separate folder 

### ISSUE THREAD

**Issue by ambiennt** [MCMrARM/mc-w10-version-launcher#90]
Maybe one could see this "issue" as an enhancement, but I found it quite useful to save the .appx's elsewhere or share online to others. In this release, the app package is deleted immediately after it is fully extracted into a folder. I would request that the output of downloading a version gives an appx and extracted folder, respectively.

**Comment by dktapps** [comment]
This was intentionally changed due to the large amount of disk space they take up (close to 500 MB per version). The appx is not needed by the launcher after initial extraction.
