### ISSUE TITLE
game crashing

### ISSUE THREAD

**Issue by Lukkasyuki** [MCMrARM/mc-w10-version-launcher#92]
When I open the game, during the Mojang Studios logo before even reaching the loading screen the game just closes without warning

**Comment by omuhu** [comment]
When I install both the latest vanilla and a beta version, the beta will crash on startup but the vanilla is fine. If I uninstall the vanilla and keep the beta installed, the beta will load just fine (beta is being installed from an appx)

**Comment by omuhu** [comment]
Narrowed the problem down for myself to RP lang files having // comments instead of # comments, looks like a change in the new betas that just crashes the game.
