### ISSUE TITLE
Says I am not Sign up for the beta when i am 

### ISSUE THREAD

**Issue by NormalOcean6686** [MCMrARM/mc-w10-version-launcher#94]
Says I am not Sign up for the beta when i am and so it wont let me download the beta
![image](https://user-images.githubusercontent.com/36484731/113485380-8fda3100-9483-11eb-994c-c78b78ee46e2.png)

**Comment by dktapps** [comment]
Do you have WUTokenHelper.dll in the folder next to MCLauncher.exe?

**Comment by NormalOcean6686** [comment]
yes
 i do

**Comment by dktapps** [comment]
What version of Windows?

**Comment by NormalOcean6686** [comment]
Version 20H2
OSbuild 19042.867

**Comment by NormalOcean6686** [comment]
Edition	Windows 10 Home
Version	20H2
Installed on	‎2021-‎03-‎23
OS build	19042.867
Experience	Windows Feature Experience Pack 120.2212.551.0

**Comment by FayneAldan** [comment]
I'm having the same issue. Stable versions download fine but betas do not. I do have a `WUTokenHelper.dll` next to my `MCLauncher.exe`.
```
Edition 	Windows 10 Pro
Version 	20H2
Installed on	‎12/‎22/‎2020
OS build	19042.906
Experience	Windows Feature Experience Pack 120.2212.1070.0
```

**Comment by dktapps** [comment]
Can you try installing this: https://aka.ms/vs/16/release/vc_redist.x64.exe

I'm shooting in the dark here so y'all are going to have to help me to help you.

**Comment by FayneAldan** [comment]
Didn't help.

**Comment by dktapps** [comment]
Am I correct in guessing you don't have Visual Studio installed?

**Comment by FayneAldan** [comment]
I have Visual Studio 2019 and VS Code installed.

**Comment by dktapps** [comment]
I've just released a new build to address a problem with WUTokenHelper. Please try it and let me know if it fixes the problem.

**Comment by FayneAldan** [comment]
Hello. The new build fixed the problem for me.

**Comment by dktapps** [comment]
Thanks. Closing this as fixed.
