### ISSUE TITLE
Minecraft RTX Beta Versions missing

### ISSUE THREAD

**Issue by monitorherocg** [MCMrARM/mc-w10-version-launcher#95]
Hey MCMrARM,

really appreciate the tool you created. Unfortunately it is missing the Beta Versions of the MC RTX.
Is there a way to get included? I am really curious for version 1.15.0.9
Hope you can help. Thanks in advance.

**Comment by DaisukeDaisuke** [comment]
> I use Google Translate.

#56
As far as I read the other issues, I have to manually add the past Minecraft version id, which seems extremely difficult.

**Comment by dktapps** [comment]
I've asked @MCMrARM to publish the tool he uses to extract this information from Windows' DataStore.edb, but you'll only be able to use it on computers that previously had the beta installed the normal way.
