### ISSUE TITLE
Add a toggle for AppX deletion/cleanup

### ISSUE THREAD

**Issue by Darthagnon** [MCMrARM/mc-w10-version-launcher#97]
I noticed commit 7838f57709a906eb59d50ff231aa5c876a8bb41e makes the program delete the AppX after automatic extraction. I was wondering if it would be possible to implement this as optional?

- Delete AppX after installation (optional; default ON)
- Automatically Extract/Install AppX after downloading (optional; default ON)

I like to archive my Minecraft AppX files for future offline installation and rollback purposes, and I prefer to extract them manually and launch them with another launcher that allows multiple profiles. It's quite annoying to have to quickly copy the AppX before it is deleted, or to have to clean up the automatic installation files.

**Comment by dktapps** [comment]
I think a better idea would be to just add a Download button to versions, so you can save them where you want to instead.

**Comment by Darthagnon** [comment]
Possibly, though that could mean people accidentally download the AppX twice - once to backup, once again if they choose to install/extract.

**Comment by dktapps** [comment]
> I prefer to extract them manually and launch them with another launcher that allows multiple profiles.

I'm not aware of any other launchers, but profiles sound like they might be worth implementing here anyway (I've periodically had issues with my options.txt getting messed up by older versions).

**Comment by Darthagnon** [comment]
MCBE Switcher by FoxyNoTail ([YouTube](https://www.youtube.com/watch?v=2vLqMFDka_o)) has a decent implementation of profiles and version switching/portable installation of MCBE. It's what I currently use; the author points to your tool, to download the AppX files necessary.

Other launchers for Minecraft Bedrock Windows 10:
- [MCBE Profiles](https://foxynotail.com/tools/)
- [MCBE Switcher](https://foxynotail.com/tools/) (seems to include MCBE Profiles)

For MCBE on Mac OSX/Linux:
- [Minecraft Bedrock Launcher](https://mcpelauncher.readthedocs.io/en/latest/), [GitHub](https://github.com/minecraft-linux/mcpelauncher-manifest)
